# Base configs
baseurl: "https://photography.Zac-Ayton.com"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by Zac Ayton"
subtitle: "See the world through my eyes!"
author: "Zac Ayton"
header:
 title: "Photography"
 subtitle: "by Zac Ayton"
footer:
 name: "Hey there, my name is Zac"
 bio: "i am a photographer from victoria. i love landscape and marco photoghraphy although i do not own a macro lense lol"
social_urls:
  discord: "Zaytonator#6251"

